namespace: prod

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: nginx
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: placeholder
